#!/usr/bin/env bash
# Stop the '4-to_infinity_and_beyond' process using pkill
pkill -f "4-to_infinity_and_beyond"
# Check if the pkill command was successful
if [ $? -eq 0 ]; then
    echo "4-to_infinity_and_beyond process has been stopped."
else
    echo "4-to_infinity_and_beyond process not found."
fi
