#!/usr/bin/env bash
# Script that starts an Apache service
# Update package list and install Apache
apt-get update
apt-get install -y apache2

# Start the Apache service
service apache2 start

# Ensure Apache starts on boot
update-rc.d apache2 defaults

# Create an HTML file with "Hello Holberton" content
echo "Hello Holberton" > /var/www/html/index.html

